### ISSUE TITLE
CSR addresses of ssp

### ISSUE THREAD

**Issue by henry-hsieh** [riscv/riscv-cfi#27] opened 2023-02-01 08:29 UTC
Spec doesn't provide the CSR addresses of `lplr` and `ssp`.

**Comment by a4lg** [comment] 2023-02-02 03:54
You don't have to close this issue (because the issue is an issue).

But, on draft specifications, instructions with no full encoding (some bits not determined) and CSRs with no value are not rare.
On such cases, such encodings and CSR values will be allocated on the later review/ratification process.

When I make test patchsets to implement such extensions for GNU Binutils, I [often use CUSTOM space for tentative allocation](https://github.com/a4lg/binutils-gdb/wiki/riscv_zisslpcfi) (based on the access control such as `URW`).

On the other hand, some specifications define tentative instruction encodings and/or CSR values on its own but assume that the actual value/encoding can change in any time.

**Comment by henry-hsieh** [comment] 2023-02-03 01:35
Thanks! I'll leave the issue opened until committee gives the CSR addresses.

**Comment by ved-rivos** [comment] 2023-02-05 17:45
Will request a tentative allocation for `lplr` and `ssp`

**Comment by henry-hsieh** [comment] 2023-05-22 03:11
According to the #104, the lpl CSR should be removed.

**Comment by ved-rivos** [comment] 2023-10-03 10:10
Address - 0x011

**Comment by ved-rivos** [comment] 2023-10-03 10:20
Included in PR #156

**Closed by ved-rivos** 2023-10-03 10:20 UTC
